### PR TITLE
make it better https://micah.social/@micah/109880430988485218

### PR DESCRIPTION
**Pull request by lsmoura**

### CODE REVIEW

**Comment by micahwalter** [comment]
I am getting two zone11's and no zone0 (no all black and two all white) ..

steps

**Comment by lsmoura** [comment]
the original code had two all-whites. I haven't changed that behaviour:

```go
			// Zone 9
			if x >= zone9 && x <= zone10 {
				img.Set(x, y, color.RGBA{225, 225, 225, 0xff})
			}

			// Zone 10
			if x >= zone10 && x <= width {
				img.Set(x, y, color.RGBA{255, 255, 255, 0xff})
			}
```

**Comment by lsmoura** [comment]
Just double-checked the code. there are actually 10 zones (ranges), not 11. Fixed the code accordingly.

**Comment by micahwalter** [comment]
Ah ok - It's a little hard to notice, but there are actually 11 zones.. The two you highlighted are **225** vs. **255** 

In the code I think it's just a matter of adding back the Zone 11, and changing line 32 to `increment := width / (zoneCount)`

**Pull request merged**
